<a href="https://colab.research.google.com/github/JiveeteshMourya/Chrun_Prediction_App/blob/main/MachineLearningWorkshop_Sem4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv("advertising.csv")
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [4]:
x = df.drop(columns = ["Sales"])
y = df["Sales"]
print(y)

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ...
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((160, 3), (40, 3), (160,), (40,))

In [7]:
from sklearn.linear_model import LinearRegression
model_lr = LinearRegression()
model_lr.fit(x_train, y_train)
LinearRegression()
y_pred = model_lr.predict(x_test)
# y_pred.shape
y_pred

array([ 9.55245706,  9.37309094, 16.18911142, 24.61620038, 21.81001954,
       19.20714581, 14.57369647, 22.74677221, 20.89661968, 23.35231794,
       16.79816702, 15.79584285, 16.83375343, 16.05782964,  5.42348198,
        7.20897366, 10.33762682, 11.94384557, 10.91054214, 18.72212432,
        9.53396393, 18.16941152, 17.12703354,  7.06854056,  9.62973088,
        9.10222871, 10.84298987, 17.07224063, 19.40263433, 16.47324935,
       20.96819947, 12.54090445, 21.46656316, 12.53452605, 19.05065561,
       21.04501646, 21.57020581, 20.92709277, 13.66615276, 20.57832524])

In [8]:
y_test

49      9.7
24      9.7
99     17.2
98     25.4
47     23.2
53     21.2
173    16.7
147    25.4
35     17.8
42     20.7
43     17.9
96     16.7
97     20.5
64     16.0
8       4.8
106     7.2
196    14.0
94     11.5
190    10.8
11     17.4
12      9.2
81     17.3
122    16.6
22      5.6
138     9.6
127    11.9
82     11.3
85     20.2
27     20.9
167    17.2
0      22.1
145    10.3
128    24.7
186    10.3
139    20.7
58     23.8
111    21.8
102    19.8
37     14.7
52     22.6
Name: Sales, dtype: float64

In [9]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(y_test, y_pred)
MAE

1.4393648320237005